name = "stats"
description = "Example proj for statistics package"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]
licenses = "MIT"
website = ""
tags = []

executables = ["stats"]

[build-switches]
"*".style_checks = "No"